use_frameworks!

platform :ios, '9.0'

target 'Masonry_LayoutGuideExt_Example' do
  pod 'Masonry+LayoutGuideExt', :path => '../'

  
  target 'Masonry_LayoutGuideExt_Tests' do
    inherit! :search_paths

    pod 'Expecta'
  end
end
